package com.upsidedowndev.mastermeme.core.presentation

import androidx.annotation.DrawableRes
import com.upsidedowndev.mastermeme.R

fun getMemeResourceList() = listOf(
    R.drawable._0_1otri4,
    R.drawable._0_2reqtg,
    R.drawable._0_3x8soh,
    R.drawable._0_8c9dbh,
    R.drawable._0__i_bet_hes_thinking_about_other_women,
    R.drawable._1_49su9f,
    R.drawable._1__third_world_skeptical_kid,
    R.drawable._1_clown_applying_makeup,
    R.drawable._1_is_this_a_pigeon,
    R.drawable._2_1yz6z4,
    R.drawable._2_2eb198,
    R.drawable._2_3eqjd8,
    R.drawable._2_7wxtd1,
    R.drawable._3_2byuiy,
    R.drawable._3__43iacv,
    R.drawable._3_jack_sparrow_being_chased,
    R.drawable._3_waiting_skeleton,
    R.drawable._4_1jgrgn,
    R.drawable._4_leonardo_dicaprio_cheers,
    R.drawable._4_running_away_balloon,
    R.drawable._4_scared,
    R.drawable._5_1op9wy,
    R.drawable._5_24zoa8,
    R.drawable._5_58eyvu,
    R.drawable._5_i_was_told_there_would_be,
    R.drawable._6_2t8r9a,
    R.drawable._6_3f0mvv,
    R.drawable._6_21ajtl,
    R.drawable._6_boardroom_meeting_suggestion,
    R.drawable._7_2w2e5e,
    R.drawable._7_3igo27,
    R.drawable._7_34vt4i,
    R.drawable._8_14p2is,
    R.drawable._8_59c1hh,
    R.drawable._8_64sz4u,
    R.drawable._8_two_buttons,
    R.drawable._9_2bbctk,
    R.drawable._9_2qx7sw,
    R.drawable._9_6rcrc1,
    R.drawable._9_6u6ylb,
    R.drawable.___1__grus_plan,
    R.drawable.___change_my_mind_,
    R.drawable.___hide_the_pain_harold,
    R.drawable.___the_rock_driving,
    R.drawable.___two_buttons,
    R.drawable.__disaster_girl,
    R.drawable.__epic_handshake,
    R.drawable.__left_exit_12_off_ramp,
    R.drawable.__sad_pablo_escobar,
)

data class MemeDefault(
    val id: Int, val name: String, @DrawableRes val memeDrawable: Int
)

fun getTemplateList() = listOf<MemeDefault>(
    MemeDefault(0,"_0_1otri4", R.drawable._0_1otri4),
    MemeDefault(1,"_0_2reqtg", R.drawable._0_2reqtg),
    MemeDefault(2,"_0_3x8soh", R.drawable._0_3x8soh),
    MemeDefault(3,"_0_8c9dbh", R.drawable._0_8c9dbh),
    MemeDefault(4,
        "_0__i_bet_hes_thinking_about_other_women",
        R.drawable._0__i_bet_hes_thinking_about_other_women
    ),
    MemeDefault(5,"_1_49su9f", R.drawable._1_49su9f),
    MemeDefault(6,"_1__third_world_skeptical_kid", R.drawable._1__third_world_skeptical_kid),
    MemeDefault(7,"_1_clown_applying_makeup", R.drawable._1_clown_applying_makeup),
    MemeDefault(8,"_1_is_this_a_pigeon", R.drawable._1_is_this_a_pigeon),
    MemeDefault(9,"_2_1yz6z4", R.drawable._2_1yz6z4),
    MemeDefault(10,"_2_2eb198", R.drawable._2_2eb198),
    MemeDefault(11,"_2_3eqjd8", R.drawable._2_3eqjd8),
    MemeDefault(12,"_2_7wxtd1", R.drawable._2_7wxtd1),
    MemeDefault(13,"_3_2byuiy", R.drawable._3_2byuiy),
    MemeDefault(14,"_3__43iacv", R.drawable._3__43iacv),
    MemeDefault(15,"_3_jack_sparrow_being_chased", R.drawable._3_jack_sparrow_being_chased),
    MemeDefault(16,"_3_waiting_skeleton", R.drawable._3_waiting_skeleton),
    MemeDefault(17,"_4_1jgrgn", R.drawable._4_1jgrgn),
    MemeDefault(18,"_4_leonardo_dicaprio_cheers", R.drawable._4_leonardo_dicaprio_cheers),
    MemeDefault(19,"_4_running_away_balloon", R.drawable._4_running_away_balloon),
    MemeDefault(20,"_4_scared", R.drawable._4_scared),
    MemeDefault(21,"_5_1op9wy", R.drawable._5_1op9wy),
    MemeDefault(22,"_5_24zoa8", R.drawable._5_24zoa8),
    MemeDefault(23,"_5_58eyvu", R.drawable._5_58eyvu),
    MemeDefault(24,"_5_i_was_told_there_would_be", R.drawable._5_i_was_told_there_would_be)
//    R.drawable._6_2t8r9a,
//    R.drawable._6_3f0mvv,
//    R.drawable._6_21ajtl,
//    R.drawable._6_boardroom_meeting_suggestion,
//    R.drawable._7_2w2e5e,
//    R.drawable._7_3igo27,
//    R.drawable._7_34vt4i,
//    R.drawable._8_14p2is,
//    R.drawable._8_59c1hh,
//    R.drawable._8_64sz4u,
//    R.drawable._8_two_buttons,
//    R.drawable._9_2bbctk,
//    R.drawable._9_2qx7sw,
//    R.drawable._9_6rcrc1,
//    R.drawable._9_6u6ylb,
//    R.drawable.___1__grus_plan,
//    R.drawable.___change_my_mind_,
//    R.drawable.___hide_the_pain_harold,
//    R.drawable.___the_rock_driving,
//    R.drawable.___two_buttons,
//    R.drawable.__disaster_girl,
//    R.drawable.__epic_handshake,
//    R.drawable.__left_exit_12_off_ramp,
//    R.drawable.__sad_pablo_escobar,
)

